replicaCount: 1
image:
  repository: mintr124/discovery-server
  tag: "6455f6b94bd6b293a01a63d76ebf44dc9e47cb28"
  pullPolicy: IfNotPresent
service:
  name: "discovery-server"
  type: NodePort
  port: 8761
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
