replicaCount: 1
image:
  repository: mintr124/api-gateway
  tag: "cd18eb70a3df662a9406dca77c04207b6e174ddc"
  pullPolicy: IfNotPresent
service:
  name: "api-gateway"
  type: NodePort
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
