replicaCount: 1
image:
  repository: mintr124/api-gateway
  tag: "0d7f471e09c84e178d9f6c50d37d7c11919dcd99"
  pullPolicy: IfNotPresent
service:
  name: "api-gateway"
  type: NodePort
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
