replicaCount: 1
image:
  repository: mintr124/api-gateway
  tag: "a75d75b9472d70362dbeda4e0ead349dd8e690f0"
  pullPolicy: IfNotPresent
service:
  name: "api-gateway"
  type: NodePort
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
