replicaCount: 1
image:
  repository: mintr124/api-gateway
  tag: "f1699f5880c32314dfab119f6655a31ef680116e"
  pullPolicy: IfNotPresent
service:
  name: "api-gateway"
  type: NodePort
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
