replicaCount: 1
image:
  repository: mintr124/api-gateway
  tag: "0753032af6f0319cd8b611ed689490a149e5857f"
  pullPolicy: IfNotPresent
service:
  name: "api-gateway"
  type: NodePort
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
