replicaCount: 1
image:
  repository: mintr124/api-gateway
  tag: "0d40386176eb8e339fb3d28c8e3d3f4c39f7b33c"
  pullPolicy: IfNotPresent
service:
  name: "api-gateway"
  type: NodePort
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
